project:
  type: website
  output-dir: docs

website:
  title: the ADU blog
  favicon: favicon.png
  google-analytics: "G-CNN34L2RWE"
  open-graph: true
  cookie-consent:
    type: express
    # style: headline
    palette: dark
  navbar:
    search: true
    right:
      - text: "blog"
        file: index.qmd
      - text: "about"
        file: about.qmd
      - icon: window
        href: https://autonomy.work/adu/
        target: _blank
      - icon: github
        href: https://github.com/Autonomy-Data-Unit
        target: _blank
      - icon: twitter
        href: https://twitter.com/Autonomy_UK
        target: _blank
      - icon: instagram
        href: https://www.instagram.com/autonomy.uk/
        target: _blank
format:
  html:
    grid: 
      body-width: 1100px
      sidebar-width: 250px
      margin-width: 250px
    include-in-header: header_modify.html
    theme:
      light:
        - simplex
        - custom.scss
      #dark:
      #  - simplex
      #  - custom.scss
      #  - theme-dark.scss
    css: styles.css

# Potential themes to use:
# lux, morph, litera, simplex

